#include "sys.h" 
//////////////////////////////////////////////////////////////////////////////////
uint8_t pinEnabled[96];

const PinDescription g_APinDescription[]=
{
	{ NULL, NULL, NULL, NULL, NULL, NULL, NULL},
  { GPIOA, GPIO_PIN_0,RCC_CLK_GPIOA, ADC_CHANNEL_0, NULL, TIM_CHANNEL_1}, // 0     //      
  { GPIOA, GPIO_PIN_1,RCC_CLK_GPIOA, ADC_CHANNEL_1, TIM2, TIM_CHANNEL_2}, // 1         // 
  { GPIOA, GPIO_PIN_2,RCC_CLK_GPIOA, ADC_CHANNEL_2, TIM2, TIM_CHANNEL_3}, // 2
	{ GPIOA, GPIO_PIN_3,RCC_CLK_GPIOA, ADC_CHANNEL_3, TIM2, TIM_CHANNEL_4}, // 3     //      
  { GPIOA, GPIO_PIN_4,RCC_CLK_GPIOA, ADC_CHANNEL_4, NULL, NULL}, // 4         // 
  { GPIOA, GPIO_PIN_5,RCC_CLK_GPIOA, ADC_CHANNEL_5, NULL, NULL}, // 5
	{ GPIOA, GPIO_PIN_6,RCC_CLK_GPIOA, ADC_CHANNEL_6, TIM3, TIM_CHANNEL_1}, // 6     //      
  { GPIOA, GPIO_PIN_7,RCC_CLK_GPIOA, ADC_CHANNEL_7, TIM3, TIM_CHANNEL_2}, // 7         // 
  { GPIOA, GPIO_PIN_8,RCC_CLK_GPIOA, NULL, TIM1, TIM_CHANNEL_1}, // 8
	{ GPIOA, GPIO_PIN_9,RCC_CLK_GPIOA, NULL, TIM1, TIM_CHANNEL_2}, // 9     //      
  { GPIOA, GPIO_PIN_10,RCC_CLK_GPIOA,NULL, TIM1, TIM_CHANNEL_3}, // 10         // 
  { GPIOA, GPIO_PIN_11,RCC_CLK_GPIOA,NULL, TIM1, TIM_CHANNEL_4}, // 11
	{ GPIOA, GPIO_PIN_12,RCC_CLK_GPIOA,NULL, NULL, NULL}, // 12    //      
  { GPIOA, GPIO_PIN_13,RCC_CLK_GPIOA,NULL, NULL, NULL}, // 13        // 
  { GPIOA, GPIO_PIN_14,RCC_CLK_GPIOA,NULL, NULL, NULL}, // 14
	{ GPIOA, GPIO_PIN_15,RCC_CLK_GPIOA,NULL, NULL, NULL}, // 15
	
	{ GPIOB, GPIO_PIN_0,RCC_CLK_GPIOB, ADC_CHANNEL_8, TIM3, TIM_CHANNEL_3}, // 0     //      
  { GPIOB, GPIO_PIN_1,RCC_CLK_GPIOB, ADC_CHANNEL_9, TIM3, TIM_CHANNEL_4}, // 1         // 
  { GPIOB, GPIO_PIN_2,RCC_CLK_GPIOB,NULL, NULL, NULL}, // 2
	{ GPIOB, GPIO_PIN_3,RCC_CLK_GPIOB, NULL, TIM2, TIM_CHANNEL_2}, // 3     //      
  { GPIOB, GPIO_PIN_4,RCC_CLK_GPIOB, NULL, TIM3, TIM_CHANNEL_1}, // 4         // 
  { GPIOB, GPIO_PIN_5,RCC_CLK_GPIOB, NULL, TIM3, TIM_CHANNEL_2}, // 5
	{ GPIOB, GPIO_PIN_6,RCC_CLK_GPIOB, NULL, TIM4, TIM_CHANNEL_1,I2C1}, // 6     //      
  { GPIOB, GPIO_PIN_7,RCC_CLK_GPIOB, NULL, TIM4, TIM_CHANNEL_2,I2C1}, // 7         // 
  { GPIOB, GPIO_PIN_8,RCC_CLK_GPIOB, NULL, NULL, TIM_CHANNEL_1,I2C1}, // 8//TIM10
	{ GPIOB, GPIO_PIN_9,RCC_CLK_GPIOB, NULL, NULL, TIM_CHANNEL_1,I2C1}, // 9     //TIM11      
  { GPIOB, GPIO_PIN_10,RCC_CLK_GPIOB, NULL, TIM2, TIM_CHANNEL_3,I2C2}, // 10         // 
  { GPIOB, GPIO_PIN_11,RCC_CLK_GPIOB, NULL, TIM2, TIM_CHANNEL_4,I2C2}, // 11
	{ GPIOB, GPIO_PIN_12,RCC_CLK_GPIOB,NULL, NULL, NULL}, // 12    //      
  { GPIOB, GPIO_PIN_13,RCC_CLK_GPIOB,NULL, NULL, NULL}, // 13        // 
  { GPIOB, GPIO_PIN_14,RCC_CLK_GPIOB, NULL, NULL, TIM_CHANNEL_1}, // 14//TIM12
	{ GPIOB, GPIO_PIN_15,RCC_CLK_GPIOB, NULL, NULL, TIM_CHANNEL_2}, // 15//TIM12
	
	{ GPIOC, GPIO_PIN_0,RCC_CLK_GPIOC, ADC_CHANNEL_10, NULL, NULL}, // 0     //      
  { GPIOC, GPIO_PIN_1,RCC_CLK_GPIOC, ADC_CHANNEL_11, NULL, NULL}, // 1         // 
  { GPIOC, GPIO_PIN_2,RCC_CLK_GPIOC, ADC_CHANNEL_12, NULL, NULL}, // 2
	{ GPIOC, GPIO_PIN_3,RCC_CLK_GPIOC, ADC_CHANNEL_13, NULL, NULL}, // 3     //      
  { GPIOC, GPIO_PIN_4,RCC_CLK_GPIOC, ADC_CHANNEL_14, NULL, NULL}, // 4         // 
  { GPIOC, GPIO_PIN_5,RCC_CLK_GPIOC, ADC_CHANNEL_14, NULL, NULL}, // 5
	{ GPIOC, GPIO_PIN_6,RCC_CLK_GPIOC, NULL, NULL, TIM_CHANNEL_1}, // 6     // TIM8     
  { GPIOC, GPIO_PIN_7,RCC_CLK_GPIOC, NULL, NULL, TIM_CHANNEL_2}, // 7         // TIM8
  { GPIOC, GPIO_PIN_8,RCC_CLK_GPIOC, NULL, NULL, TIM_CHANNEL_3}, // 8		//TIM8
	{ GPIOC, GPIO_PIN_9,RCC_CLK_GPIOC, NULL, NULL, TIM_CHANNEL_4}, // 9     //   TIM8   
  { GPIOC, GPIO_PIN_10,RCC_CLK_GPIOC,NULL, NULL, NULL}, // 10         // 
  { GPIOC, GPIO_PIN_11,RCC_CLK_GPIOC,NULL, NULL, NULL}, // 11
	{ GPIOC, GPIO_PIN_12,RCC_CLK_GPIOC,NULL, NULL, NULL}, // 12    //      
  { GPIOC, GPIO_PIN_13,RCC_CLK_GPIOC,NULL, NULL, NULL}, // 13        // 
  { GPIOC, GPIO_PIN_14,RCC_CLK_GPIOC,NULL, NULL, NULL}, // 14
	{ GPIOC, GPIO_PIN_15,RCC_CLK_GPIOC,NULL, NULL, NULL}, // 15
	
	{ GPIOD, GPIO_PIN_0,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 0     //      
  { GPIOD, GPIO_PIN_1,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 1         // 
  { GPIOD, GPIO_PIN_2,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 2
	{ GPIOD, GPIO_PIN_3,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 3     //      
  { GPIOD, GPIO_PIN_4,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 4         // 
  { GPIOD, GPIO_PIN_5,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 5
	{ GPIOD, GPIO_PIN_6,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 6     //      
  { GPIOD, GPIO_PIN_7,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 7         // 
  { GPIOD, GPIO_PIN_8,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 8
	{ GPIOD, GPIO_PIN_9,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 9     //      
  { GPIOD, GPIO_PIN_10,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 10         // 
  { GPIOD, GPIO_PIN_11,RCC_CLK_GPIOD,NULL, NULL, NULL}, // 11
	{ GPIOD, GPIO_PIN_12,RCC_CLK_GPIOD, NULL, TIM4, TIM_CHANNEL_1}, // 12    //      
  { GPIOD, GPIO_PIN_13,RCC_CLK_GPIOD, NULL, TIM4, TIM_CHANNEL_2}, // 13        // 
  { GPIOD, GPIO_PIN_14,RCC_CLK_GPIOD, NULL, TIM4, TIM_CHANNEL_3}, // 14
	{ GPIOD, GPIO_PIN_15,RCC_CLK_GPIOD, NULL, TIM4, TIM_CHANNEL_4}, // 15
	
	{ GPIOE, GPIO_PIN_0,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 0     //      
  { GPIOE, GPIO_PIN_1,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 1         // 
  { GPIOE, GPIO_PIN_2,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 2
	{ GPIOE, GPIO_PIN_3,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 3     //      
  { GPIOE, GPIO_PIN_4,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 4         // 
  { GPIOE, GPIO_PIN_5,RCC_CLK_GPIOE, NULL, NULL, TIM_CHANNEL_1}, // 5
	{ GPIOE, GPIO_PIN_6,RCC_CLK_GPIOE, NULL, NULL, TIM_CHANNEL_2}, // 6     //      
  { GPIOE, GPIO_PIN_7,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 7         // 
  { GPIOE, GPIO_PIN_8,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 8
	{ GPIOE, GPIO_PIN_9,RCC_CLK_GPIOE, NULL, TIM1, TIM_CHANNEL_1}, // 9     //      
  { GPIOE, GPIO_PIN_10,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 10         // 
  { GPIOE, GPIO_PIN_11,RCC_CLK_GPIOE, NULL, TIM1, TIM_CHANNEL_2}, // 11
	{ GPIOE, GPIO_PIN_12,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 12    //      
  { GPIOE, GPIO_PIN_13,RCC_CLK_GPIOE, NULL, TIM1, TIM_CHANNEL_3}, // 13        // 
  { GPIOE, GPIO_PIN_14,RCC_CLK_GPIOE, NULL, TIM1, TIM_CHANNEL_4}, // 14
	{ GPIOE, GPIO_PIN_15,RCC_CLK_GPIOE,NULL, NULL, NULL}, // 15
	
	#ifdef GPIOF
	{ GPIOF, GPIO_PIN_0,RCC_CLK_GPIOF}, // 0     //      
  { GPIOF, GPIO_PIN_1,RCC_CLK_GPIOF}, // 1         // 
  { GPIOF, GPIO_PIN_2,RCC_CLK_GPIOF}, // 2
	{ GPIOF, GPIO_PIN_3,RCC_CLK_GPIOF}, // 3     //      
  { GPIOF, GPIO_PIN_4,RCC_CLK_GPIOF}, // 4         // 
  { GPIOF, GPIO_PIN_5,RCC_CLK_GPIOF}, // 5
	{ GPIOF, GPIO_PIN_6,RCC_CLK_GPIOF}, // 6     //      
  { GPIOF, GPIO_PIN_7,RCC_CLK_GPIOF}, // 7         // 
  { GPIOF, GPIO_PIN_8,RCC_CLK_GPIOF}, // 8
	{ GPIOF, GPIO_PIN_9,RCC_CLK_GPIOF}, // 9     //      
  { GPIOF, GPIO_PIN_10,RCC_CLK_GPIOF}, // 10         // 
  { GPIOF, GPIO_PIN_11,RCC_CLK_GPIOF}, // 11
	{ GPIOF, GPIO_PIN_12,RCC_CLK_GPIOF}, // 12    //      
  { GPIOF, GPIO_PIN_13,RCC_CLK_GPIOF}, // 13        // 
  { GPIOF, GPIO_PIN_14,RCC_CLK_GPIOF}, // 14
	{ GPIOF, GPIO_PIN_15,RCC_CLK_GPIOF}, // 15		//95
	#endif
	
} ;
////////////////////////////////////////////////////////////////////////

